[build]
  base = "client"
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_SOCKET_URL = "https://your-backend-url.com"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.com/api/:splat"
  status = 200

[[redirects]]
  from = "/socket.io/*"
  to = "https://your-backend-url.com/socket.io/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 